language: swift
osx_image: xcode12.4
script: xcodebuild clean build test -project assertYourSelf.xcodeproj -scheme assertYourSelf -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 12,OS=14.4'
